#!/usr/bin/env bash
# script to report information about server domains

check_domain() {
  local domain="$1" subdomain="$2"
  record=$(dig "$subdomain.$domain" +short | grep -o '[A-Za-z]*')
  destination=$(dig "$subdomain.$domain" +short | cut -d ' ' -f 4)
  if [[ ! -z "$record" && ! -z "$destination" ]]; then
    echo "The subdomain $subdomain is a $record record and points to $destination"
  fi
}

if [ $# -eq 1 ]; then
  for subdomain in www lb-01 web-01 web-02; do
    check_domain "$1" "$subdomain"
  done
elif [ $# -eq 2 ]; then
  check_domain "$1" "$2"
else
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi
