#!/usr/bin/env bash
# Configure Nginx server

apt-get update
apt-get upgrade
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/^}$/i \ \\n\tlocation /redirect_me {\\n\t\treturn 301 https://x.com/Ali_Taha_AMT\\n\t}" /etc/nginx/sites-available/default
service nginx restart
