#!/usr/bin/env bash
# Configure Nginx server

apt-get update
apt-get upgrade
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/^}$/i \ \n\trewrite ^/redirect_me$ https://x.com/Ali_Taha_AMT permanent;" /etc/nginx/sites-available/default
service nginx restart
