#!/usr/bin/env bash
# Configure Nginx server

apt-get update
apt-get upgrade
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "53i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=Ofm57qtjulk&t=528s permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
