#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

apt-get update
apt-get upgrade
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/^}$/i \ \\n\tlocation /redirect_me {\\n\t\treturn 301 https://x.com/Ali_Taha_AMT;\\n\t}" /etc/nginx/sites-available/default
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/^}$/i \ \\n\terror_page 404 /404.html;" /etc/nginx/sites-available/default
service nginx restart
