#!/usr/bin/env bash
# Install and configure HAproxy

apt-get update
apt-get upgrade
apt-get install haproxy
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 100.26.152.157:80
        server 64820-web-02 52.86.102.6:80
' >> /etc/haproxy/haproxy.cfg
systemctl restart haproxy.service
