#!/usr/bin/env bash
#When passing the argument start:
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process started
#When passing the argument stop:
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Displays manage_my_process stopped
#When passing the argument restart
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process restarted
#Displays Usage: manage_my_process {start|stop|restart} 
#if any other argument or no argument is passed

F="/var/run/my_process.pid"

create()
{
    sudo touch $F
    sudo bash -c "echo $$ > $F"
}

if [ "$1" == "start" ]; then
    create
    ./manage_my_process &
    echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
    [ -e "/var/run/my_process.pid" ] && sudo pkill -f "./manage_my_process" && rm /var/run/my_process.pid
    echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
    $0 stop >& /dev/null
    $0 start >& /dev/null
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
